spring.application.name=reserva

# Força o uso do H2 em memória simulando a sintaxe e comportamento do MySQL
spring.datasource.url=jdbc:h2:mem:reservadb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Configurações JPA para testes isolados
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
# Desativa o Flyway para os testes em memória rodarem sem conflitos
spring.flyway.enabled=false